spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}AQB9yWwO7z0kBTEbu+sy8ReCJoTEQSut7Mpne9iwDW+/lrCFf24W+1rH2PBcw6wLVIZD/TzARS9IwqF7NRcKVhuiwNLoUKBt1wkOk9v5oDfiCy3xtFmxp/VOrIPGcMT+fK2nEkxiPKFTw1o9qUr9C2jmlxD9PC0x4xb0IyjYQJ3SHmw+mLPHzdeLcWnbtIvYafITtGypVaA2zgaf+59ZyNN+Jicbaoz9AVHWh0Hh6dSNcYS1E6gq0GckrQtIInKxrVmy5OUmAm+lpTs4/dPQG+bRJWJNY4kqtTRjz2+qEMs6aYjxFdcRHH6HVRkzoOA1yDMrPHO94AcKfDJD/RcygkVAjyAmzka0QdVBV/o0JMpGcQ2dE9+m/1Nbnn/yWfvwlyM='
token:
  expiration_time: 86400000
  secret: my_token_#1

gateway:
  ip: 192.168.56.1
  
